// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBumx_JIAstEaZYjkRE5BsQJdvfkO16apU',
    appId: '1:530664233262:android:e477ce7b65e724ec8782bf',
    messagingSenderId: '530664233262',
    projectId: 'as-des-mobile',
    storageBucket: 'as-des-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP_TQ-7Y4noaEYAkZx8HnddlxL_-WF1uI',
    appId: '1:530664233262:ios:7bf7832c1ea246918782bf',
    messagingSenderId: '530664233262',
    projectId: 'as-des-mobile',
    storageBucket: 'as-des-mobile.firebasestorage.app',
    iosBundleId: 'com.example.projetoAp2',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFujNpsW_TLU2A_4yn1k12jTW0emcchlY',
    appId: '1:530664233262:web:6193277fad5fa5128782bf',
    messagingSenderId: '530664233262',
    projectId: 'as-des-mobile',
    authDomain: 'as-des-mobile.firebaseapp.com',
    storageBucket: 'as-des-mobile.firebasestorage.app',
  );

}